### PR TITLE
Add TFileCacheWrite and make cacheSize an option for ROOTOutputer.

### PR DESCRIPTION
**Pull request by gartung**
Resubmit PR accidentally closed

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@gartung for the future, please let us do a review of code before merging? In general, it is better to allow someone else do the merge rather than having the author do the merge.

**Comment by gartung** [comment]
Sorry. I can reset the head of master if needed.

**Comment by Dr15Jones** [comment]
It's OK. Just talking about the future.

**Comment by gartung** [comment]
Please re-review in https://github.com/hep-cce2/root_serialization/pull/44

**Pull request merged**
