### PR TITLE
Add TFileCacheWrite and make cacheSize an option for ROOTOutputer  and TBufferMergerROOTOutputer

### PR DESCRIPTION
**Pull request by gartung**
Resubmit of https://github.com/hep-cce2/root_serialization/pull/44 for code review after resetting head of master

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones @pcanal This change to TBuffferMergerRootOutputer seems to improve the writing time. Maybe a similar static function is needed for RootOutputer as well.

**Comment by gartung** [comment]
The use of the TFileCacheWrite does seem produce a marginal speedup 
```
----------
Source RepeatingRootSource=/global/cscratch1/sd/gartung/250202_181_MINIAOD_100ev.root:repeat=100
Outputer TBufferMergerRootOutputer=/var/opt/cray/dws/mounts/batch/58248087_striped_scratch//test_1_stress.root:splitLevel=99:compressionLevel=4:compressionAlgorithm=LZMA:autoFlush=900:cacheSize=10485760
Waiter 
# threads 8
# concurrent events 8
use ROOT IMT true
Event processing time: 125158756us
number events: 40000
----------

Source time: 18408us

end write
file close
TBufferMergerRootOutputer fill time: 983483113us
TBufferMergerRootOutputer write time: 0us
TBufferMergerRootOutputer end write time: 40581802us
TBufferMergerRootOutputer end close time: 142373us
TBufferMergerRootOutputer total time: 1024064915us



----------
Source RepeatingRootSource=/global/cscratch1/sd/gartung/250202_181_MINIAOD_100ev.root:repeat=100
Outputer TBufferMergerRootOutputer=/var/opt/cray/dws/mounts/batch/58248088_striped_scratch//test_1_stress.root:splitLevel=99:compressionLevel=4:compressionAlgorithm=LZMA:autoFlush=900:cacheSize=0
Waiter 
# threads 8
# concurrent events 8
use ROOT IMT true
Event processing time: 131401241us
number events: 40000
----------

Source time: 22364us

end write
Tue Apr 26 09:45:40 2022: [unset]:_pmi_alps_init:alps_get_placement_info returned with error -1
Tue Apr 26 09:45:40 2022: [unset]:_pmi_init:_pmi_alps_init returned -1
file close
TBufferMergerRootOutputer fill time: 1034634135us
TBufferMergerRootOutputer write time: 0us
TBufferMergerRootOutputer end write time: 43652830us
TBufferMergerRootOutputer end close time: 145161us
TBufferMergerRootOutputer total time: 1078286965us

```

**Comment by gartung** [comment]
@Dr15Jones can this be merged?

**Comment by gartung** [comment]
Done

**Comment by Dr15Jones** [comment]
Thanks for adding the full documentation for `TBufferMergerRootOutputer`, I hadn't realized I had failed to write it originally.

**Pull request merged**
