### PR TITLE
Switch to using a ComponentFactory

### PR DESCRIPTION
**Pull request by Dr15Jones**
This is a first draft for making it easier to add new Outputers and Sources to the job. Instead of having to edit the appropriate *Factory function, one just instantiates the appropriate `Maker` for the appropriate `Factory` and then makes sure the .o file containing the instance is linked with the executable.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
All the changes are now in. One no longer has to edit `outputerFactoryGenerator.cc` to add a new Outputer. Now the configuration objects and registration of the Outputer can be done in the same .cc file as the code for the Outputer.

**Comment by Dr15Jones** [comment]
I've also converted all the Sources to use the same factory system. That is on another branch and I'll wait for this PR before making another one.

**Comment by Dr15Jones** [comment]
I decided to go ahead and add the Source changes here as well

**Review by sabasehrish — APPROVED** [review]
Looks good to me (didn't realize that Source changes were also in the same PR until late).

**Pull request merged**
